const LAST_CHECKED = "2026-05-16";

const routeTemplates = [];

const allItems = [
  {
    id: "bandinis-barcelona",
    name: "Bandini's",
    kind: "bar",
    lat: 41.376641,
    lng: 2.1609297,
    area: "sant-antoni",
    tags: ["mat", "vin", "cocktail", "nattliv", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bandinis", "bandini", "carrer de manso", "sant antoni", "eixample edge"],
  },
  {
    id: "mercat-sant-antoni",
    name: "Mercat de Sant Antoni",
    kind: "market",
    lat: 41.3786255,
    lng: 2.1620493,
    area: "sant-antoni",
    tags: ["market", "mat", "lokalt", "vintage", "second_hand"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat de sant antoni", "sant antoni market", "mercat sant antoni"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 2, 3, 4, 5, 6],
      weakWeekdays: [0],
      daySensitivity: "medium",
      verifyRecommended: true,
    },
  },
  {
    id: "bar-calders",
    name: "Bar Calders",
    kind: "bar",
    lat: 41.3764788,
    lng: 2.1623937,
    area: "sant-antoni",
    tags: ["vin", "mat", "nattliv", "aperitivo", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bar calders", "calders", "carrer del parlament", "sant antoni"],
  },
  {
    id: "federal-parlament",
    name: "Federal Cafe Parlament",
    kind: "cafe",
    lat: 41.3768982,
    lng: 2.1628879,
    area: "sant-antoni",
    tags: ["mat", "lokalt", "low-key"],
    weatherTags: ["all-weather", "morning"],
    closedWeekdays: [],
    searchTerms: ["federal cafe", "federal parlament", "carrer del parlament", "sant antoni"],
  },
  {
    id: "mercat-encants",
    name: "Mercat dels Encants",
    kind: "market",
    lat: 41.4010304,
    lng: 2.1861738,
    area: "eixample",
    tags: ["market", "second_hand", "vintage", "shopping", "antique", "lokalt"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat dels encants", "els encants", "encants", "fira de bellcaire"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 3, 5, 6],
      weakWeekdays: [0, 2, 4],
      daySensitivity: "high",
      verifyRecommended: true,
    },
  },
  {
    id: "casa-vicens",
    name: "Casa Vicens",
    kind: "museum",
    lat: 41.4035057,
    lng: 2.1506255,
    area: "gracia",
    tags: ["kultur", "klassiker", "arkitektur"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [],
    searchTerms: ["casa vicens", "gaudi", "gracia"],
  },
  {
    id: "cines-verdi",
    name: "Cines Verdi",
    kind: "cinema",
    lat: 41.4040146,
    lng: 2.1568811,
    area: "gracia",
    tags: ["kultur", "nattliv", "low-key"],
    weatherTags: ["rain", "evening"],
    closedWeekdays: [],
    searchTerms: ["cines verdi", "cinema verdi", "verdi", "gracia"],
  },
  {
    id: "bodega-quimet",
    name: "Bodega Quimet",
    kind: "bar",
    lat: 41.3992157,
    lng: 2.1546399,
    area: "gracia",
    tags: ["vin", "mat", "lokalt", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bodega quimet", "quimet gracia", "carrer de vic", "gracia"],
  },
  {
    id: "placa-del-sol",
    name: "Plaça del Sol",
    kind: "square",
    lat: 41.4016246,
    lng: 2.1567108,
    area: "gracia",
    tags: ["lokalt", "nattliv", "low-key", "hidden gems"],
    weatherTags: ["sun", "evening"],
    closedWeekdays: [],
    searchTerms: ["placa del sol", "plaça del sol", "gracia square", "vila de gracia"],
  },
  {
    id: "mercat-santa-caterina",
    name: "Mercat de Santa Caterina",
    kind: "market",
    lat: 41.3861363,
    lng: 2.1785048,
    area: "born-sant-pere-santa-caterina",
    tags: ["market", "mat", "lokalt", "kultur"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat de santa caterina", "santa caterina market", "mercat santa caterina"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 2, 3, 4, 5, 6],
      weakWeekdays: [0],
      daySensitivity: "medium",
      verifyRecommended: true,
    },
  },
  {
    id: "santa-maria-del-mar",
    name: "Santa Maria del Mar",
    kind: "church",
    lat: 41.3837802,
    lng: 2.1820062,
    area: "born-sant-pere-santa-caterina",
    tags: ["kultur", "kyrkor", "klassiker"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [],
    searchTerms: ["santa maria del mar", "basilica santa maria del mar", "el born"],
  },
  {
    id: "museu-picasso",
    name: "Museu Picasso",
    kind: "museum",
    lat: 41.3851039,
    lng: 2.1812015,
    area: "born-sant-pere-santa-caterina",
    tags: ["kultur", "klassiker", "museum"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [1],
    searchTerms: ["museu picasso", "picasso museum", "museo picasso", "el born"],
  },
  {
    id: "bar-brutal",
    name: "Bar Brutal",
    kind: "bar",
    lat: 41.3852677,
    lng: 2.1805362,
    area: "born-sant-pere-santa-caterina",
    tags: ["vin", "mat", "nattliv", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bar brutal", "brutal barcelona", "carrer de la princesa", "el born"],
  },
  {
    id: "placa-sant-felip-neri",
    name: "Plaça de Sant Felip Neri",
    kind: "square",
    lat: 41.3833846,
    lng: 2.1750998,
    area: "gothic",
    tags: ["kultur", "hidden gems", "low-key"],
    weatherTags: ["sun", "mild"],
    closedWeekdays: [],
    searchTerms: ["placa sant felip neri", "plaça de sant felip neri", "gothic quarter"],
  },
  {
    id: "la-manual-alpargatera",
    name: "La Manual Alpargatera",
    kind: "shop",
    lat: 41.3815528,
    lng: 2.1761225,
    area: "gothic",
    tags: ["shopping", "kultur", "klassiker", "lokalt"],
    weatherTags: ["all-weather"],
    closedWeekdays: [],
    searchTerms: ["la manual alpargatera", "alpargatera", "espadrilles", "gothic quarter"],
    availability: {
      kind: "shop",
      daySensitivity: "low",
      verifyRecommended: true,
    },
  },
  {
    id: "la-plata",
    name: "La Plata",
    kind: "bar",
    lat: 41.3804049,
    lng: 2.1805946,
    area: "gothic",
    tags: ["mat", "vin", "lokalt", "klassiker"],
    weatherTags: ["all-weather"],
    closedWeekdays: [],
    searchTerms: ["la plata", "carrer de la merce", "gothic quarter"],
  },
  {
    id: "cccb",
    name: "CCCB",
    kind: "museum",
    lat: 41.383693,
    lng: 2.1662438,
    area: "raval",
    tags: ["kultur", "museum", "hidden gems"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [1],
    searchTerms: ["cccb", "centre de cultura contemporania", "montalegre", "raval"],
  },
  {
    id: "bar-marsella",
    name: "Bar Marsella",
    kind: "bar",
    lat: 41.3782418,
    lng: 2.1712432,
    area: "raval",
    tags: ["nattliv", "cocktail", "klassiker", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bar marsella", "marsella", "absinthe", "raval"],
  },
  {
    id: "quimet-quimet",
    name: "Quimet & Quimet",
    kind: "bar",
    lat: 41.374222,
    lng: 2.1657389,
    area: "poble-sec",
    tags: ["mat", "vin", "klassiker", "low-key"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["quimet quimet", "quimet & quimet", "poble-sec", "poeta cabanyes"],
  },
  {
    id: "sala-apolo",
    name: "Sala Apolo",
    kind: "music",
    lat: 41.3743908,
    lng: 2.1695606,
    area: "poble-sec",
    tags: ["nattliv", "party", "kultur", "music"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["sala apolo", "apolo", "nou de la rambla", "poble-sec"],
  },
  {
    id: "fundacio-joan-miro",
    name: "Fundació Joan Miró",
    kind: "museum",
    lat: 41.3686445,
    lng: 2.1600839,
    area: "montjuic",
    tags: ["kultur", "museum", "utsikt", "klassiker"],
    weatherTags: ["rain", "hot", "sun"],
    closedWeekdays: [1],
    searchTerms: ["fundacio joan miro", "fundació joan miró", "joan miro", "montjuic"],
  },
  {
    id: "mnac",
    name: "MNAC",
    kind: "museum",
    lat: 41.3684015,
    lng: 2.1534231,
    area: "montjuic",
    tags: ["kultur", "museum", "utsikt", "klassiker"],
    weatherTags: ["rain", "hot", "golden-hour"],
    closedWeekdays: [1],
    searchTerms: ["mnac", "museu nacional", "palau nacional", "montjuic"],
  },
  {
    id: "museu-can-framis",
    name: "Museu Can Framis",
    kind: "museum",
    lat: 41.4027616,
    lng: 2.1944335,
    area: "poblenou",
    tags: ["kultur", "museum", "hidden gems", "low-key"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [1],
    searchTerms: ["museu can framis", "can framis", "poblenou"],
  },
  {
    id: "palo-alto-market",
    name: "Palo Alto Market",
    kind: "event_market",
    lat: 41.4043377,
    lng: 2.2105052,
    area: "poblenou",
    tags: ["market", "event_market", "mat", "shopping", "kultur", "hidden gems"],
    weatherTags: ["all-weather", "weekend"],
    closedWeekdays: [1, 2, 3, 4, 5],
    searchTerms: ["palo alto market", "palo alto", "poblenou", "pellaires"],
    availability: {
      kind: "event_market",
      strongWeekdays: [0, 6],
      weakWeekdays: [1, 2, 3, 4, 5],
      daySensitivity: "high",
      verifyRecommended: true,
    },
  },
  {
    id: "platja-bogatell",
    name: "Platja del Bogatell",
    kind: "beach",
    lat: 41.3939544,
    lng: 2.2066734,
    area: "poblenou",
    tags: ["coast", "utsikt", "low-key", "lokalt"],
    weatherTags: ["sun", "mild", "golden-hour"],
    closedWeekdays: [],
    searchTerms: ["platja del bogatell", "bogatell beach", "beach", "poblenou"],
  },
  {
    id: "la-cova-fumada",
    name: "La Cova Fumada",
    kind: "restaurant",
    lat: 41.3792983,
    lng: 2.1891943,
    area: "barceloneta",
    tags: ["mat", "lokalt", "klassiker", "hidden gems"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["la cova fumada", "cova fumada", "barceloneta", "baluard"],
  },
];

const provenanceById = {
  "bandinis-barcelona": {
    source_url: "https://www.bandinisbarcelona.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Normal beta seed from issue #45; useful Sant Antoni food/bar anchor near the Eixample edge.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["food_anchor", "bar_anchor", "middle"],
    classification: "beta_seed",
    needs_human_verification: false,
    source_note: "Issue #45 identifies Bandini's as a beta seed; Nominatim confirmed Carrer de Manso 42 coordinates.",
  },
  "mercat-sant-antoni": {
    source_type: "osm_structured_data",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Market anchor for Sant Antoni with food and second-hand/vintage route value.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "second_hand", "market"],
    time_fit: ["morning", "lunch", "afternoon"],
    route_role: ["start", "market", "food_anchor"],
    classification: "local_anchor",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed market address and coordinates during catalog pass.",
  },
  "bar-calders": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Sant Antoni bar/food connector on Parlament, useful for soft evening routes.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["bar_anchor", "middle", "final"],
    classification: "local_anchor",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed place/address; source should be human-checked before curated launch.",
  },
  "federal-parlament": {
    source_url: "https://www.federalcafe.es/",
    source_type: "official_site",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Morning/lunch anchor on Parlament that helps Sant Antoni routes start gently.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "local_anchor"],
    time_fit: ["morning", "lunch"],
    route_role: ["start", "food_anchor"],
    classification: "practical_connector",
    needs_human_verification: true,
  },
  "mercat-encants": {
    source_url: "https://encants.cat/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Large market/second-hand anchor that can test vintage and market intents without tourist framing.",
    area: "eixample",
    macro: "central-grid",
    tags_intents: ["second_hand", "market", "shopping"],
    time_fit: ["morning", "afternoon"],
    route_role: ["market", "connector", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "casa-vicens": {
    source_url: "https://casavicens.org/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Cultural Gràcia anchor that adds architecture without defaulting to the busiest old-town loop.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["culture", "classic"],
    time_fit: ["morning", "afternoon"],
    route_role: ["start", "culture_anchor"],
    classification: "classic",
    needs_human_verification: false,
  },
  "cines-verdi": {
    source_url: "https://barcelona.cines-verdi.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Gràcia cultural/evening anchor that supports repeat-visitor and rainy-day routes.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["culture", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["middle", "final"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "bodega-quimet": {
    source_url: "https://www.bodegaquimet.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Compact Gràcia bar/food anchor for local evening drift.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["food_drink", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["bar_anchor", "final"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "placa-del-sol": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Useful Gràcia connector and evening square, especially for routes that should drift rather than checklist.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["local_anchor", "nightlife", "hidden_gems"],
    time_fit: ["afternoon", "evening"],
    route_role: ["connector", "middle"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed square coordinates; local rhythm should be human-verified.",
  },
  "mercat-santa-caterina": {
    source_type: "osm_structured_data",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Market anchor for Born/Sant Pere/Santa Caterina routes with food and old-town connector value.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["food_drink", "market", "culture"],
    time_fit: ["morning", "lunch"],
    route_role: ["market", "food_anchor", "start"],
    classification: "local_anchor",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed market address and coordinates during catalog pass.",
  },
  "santa-maria-del-mar": {
    source_url: "https://www.santamariadelmarbarcelona.org/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Culture anchor in Born that can carry church/culture intent without making a full tourist loop.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["culture"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "museu-picasso": {
    source_url: "https://museupicassobcn.cat/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Major museum anchor that helps test culture routes in Born without needing route seeds yet.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["culture"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "bar-brutal": {
    source_url: "https://www.brutalbarcelona.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Natural-wine/food anchor that supports evening routes in Born/Sant Pere.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["food_drink", "nightlife"],
    time_fit: ["evening"],
    route_role: ["food_anchor", "bar_anchor", "final"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "placa-sant-felip-neri": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Quiet Gothic connector with cultural weight, useful only when it improves old-town flow.",
    area: "gothic",
    macro: "old-town",
    tags_intents: ["culture", "hidden_gems", "low_key"],
    time_fit: ["morning", "afternoon"],
    route_role: ["connector", "culture_anchor"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed square coordinates; inclusion should remain route-useful, not checklist-driven.",
  },
  "la-manual-alpargatera": {
    source_url: "https://lamanual.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Gothic shop/craft anchor that adds local retail texture without fake hidden-gem framing.",
    area: "gothic",
    macro: "old-town",
    tags_intents: ["shopping", "culture"],
    time_fit: ["morning", "afternoon"],
    route_role: ["middle", "connector"],
    classification: "classic",
    needs_human_verification: false,
  },
  "la-plata": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Small Gothic food/bar anchor that can make old-town routes feel less generic.",
    area: "gothic",
    macro: "old-town",
    tags_intents: ["food_drink", "local_anchor"],
    time_fit: ["lunch", "evening"],
    route_role: ["food_anchor", "bar_anchor"],
    classification: "classic",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed place/address; source should be human-checked before public beta.",
  },
  cccb: {
    source_url: "https://www.cccb.org/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Raval culture anchor with strong rainy-day and repeat-visitor value.",
    area: "raval",
    macro: "old-town",
    tags_intents: ["culture"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "start", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "bar-marsella": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Historic Raval night anchor, useful with caution for late routes.",
    area: "raval",
    macro: "old-town",
    tags_intents: ["nightlife", "cocktail"],
    time_fit: ["evening", "late"],
    route_role: ["bar_anchor", "final"],
    classification: "classic",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed place/address; current operations should be human-verified.",
  },
  "quimet-quimet": {
    source_url: "https://quimetiquimet.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Poble-sec food/wine anchor that links theater, Montjuïc edge, and evening routes.",
    area: "poble-sec",
    macro: "montjuic-southwest",
    tags_intents: ["food_drink", "classic"],
    time_fit: ["lunch", "evening"],
    route_role: ["food_anchor", "bar_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "sala-apolo": {
    source_url: "https://www.sala-apolo.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Poble-sec nightlife/culture anchor for later event-aware routes.",
    area: "poble-sec",
    macro: "montjuic-southwest",
    tags_intents: ["nightlife", "culture"],
    time_fit: ["evening", "late"],
    route_role: ["final", "nightlife_place"],
    classification: "nightlife_place",
    needs_human_verification: false,
  },
  "fundacio-joan-miro": {
    source_url: "https://www.fmirobcn.org/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Montjuïc culture anchor that supports park/view arcs rather than isolated museum stops.",
    area: "montjuic",
    macro: "montjuic-southwest",
    tags_intents: ["culture", "views"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "view", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  mnac: {
    source_url: "https://www.museunacional.cat/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Culture/view anchor for Montjuïc routes and golden-hour route endings.",
    area: "montjuic",
    macro: "montjuic-southwest",
    tags_intents: ["culture", "views"],
    time_fit: ["morning", "afternoon", "golden_hour"],
    route_role: ["culture_anchor", "view", "final"],
    classification: "classic",
    needs_human_verification: false,
  },
  "museu-can-framis": {
    source_url: "https://www.fundaciovilacasas.com/en/museum/can-framis",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Poblenou culture anchor that helps routes avoid only beach/postcard logic.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["culture", "hidden_gems"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "palo-alto-market": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Event-market anchor for Poblenou design/food rhythm; high date sensitivity.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["market", "food_drink", "shopping", "culture"],
    time_fit: ["weekend", "afternoon"],
    route_role: ["market", "middle"],
    classification: "event_market",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed location; live/event schedule must be verified before user-facing route use.",
  },
  "platja-bogatell": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Coast connector that helps model beach flow as part of a day rather than as postcard content.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["views", "coast", "low_key"],
    time_fit: ["morning", "afternoon", "golden_hour"],
    route_role: ["connector", "view", "final"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed beach coordinates; seasonal fit needs later review.",
  },
  "la-cova-fumada": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Barceloneta food anchor with coast-neighborhood route value.",
    area: "barceloneta",
    macro: "coast-east",
    tags_intents: ["food_drink", "local_anchor"],
    time_fit: ["lunch", "afternoon"],
    route_role: ["food_anchor", "middle"],
    classification: "classic",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed place/address; current hours should be human-verified.",
  },
};

const normalizedItemsByName = new Map();
for (const item of allItems) {
  const aliases = [item.name, ...(item.searchTerms || [])];
  for (const alias of aliases) {
    normalizedItemsByName.set(normalizeLookup(alias), item);
  }
}

function normalizeLookup(value) {
  return String(value || "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
}

function findItemByName(name) {
  return normalizedItemsByName.get(normalizeLookup(name)) || null;
}

module.exports = {
  routeTemplates,
  allItems,
  findItemByName,
  provenanceById,
};
