const LAST_CHECKED = "2026-05-16";

const routeTemplates = [
  {
    id: "gracia-local-evening-loop",
    title: "Gràcia local evening loop",
    summary: "Gràcia med kultur, små kvartersstopp och en mjuk kvällslandning utan att överbygga området.",
    stops: ["casa-vicens", "cines-verdi", "placa-del-sol", "bodega-quimet"],
    defaultKm: 5,
    preferenceTags: ["kultur", "mat", "vin", "nattliv", "kväll", "low-key", "hidden gems", "lokalt"],
    optimizerModes: ["culture-mode", "low-key-mode", "evening-mode", "wine-crawl"],
    weatherProfile: { sun: 1, rain: 2, hot: 0, evening: 2 },
    weekdayBoost: { 3: 1, 4: 1, 5: 1, 6: 1 },
    vibeProfile: { evening: 2, culture: 2, lowKey: 3, party: 0 },
  },
  {
    id: "sant-antoni-food-bar-flow",
    title: "Sant Antoni food and bar flow",
    summary: "Sant Antoni som tät mat- och bardag med marknad, Parlament och en lugn kvällsbåge.",
    stops: ["bar-calders", "bandinis-barcelona", "mercat-sant-antoni", "federal-parlament"],
    defaultKm: 5,
    preferenceTags: ["mat", "vin", "nattliv", "kväll", "cocktail", "market", "lokalt", "low-key"],
    optimizerModes: ["bar-hop", "wine-crawl", "cocktail-night", "low-key-mode", "evening-mode"],
    weatherProfile: { sun: 1, rain: 2, hot: 0, evening: 3 },
    weekdayBoost: { 2: 1, 3: 1, 4: 1, 5: 1, 6: 1 },
    vibeProfile: { evening: 3, culture: 0, lowKey: 2, party: 2 },
  },
  {
    id: "born-santa-caterina-culture-wine-loop",
    title: "Born and Santa Caterina culture to wine",
    summary: "Marknad, museum, kyrkorum och vinbar i en tät gammalstadsslinga som fortfarande känns användbar.",
    stops: ["mercat-santa-caterina", "museu-picasso", "santa-maria-del-mar", "bar-brutal"],
    defaultKm: 5,
    preferenceTags: ["kultur", "vin", "market", "kyrkor", "low-key"],
    optimizerModes: ["culture", "wine-crawl", "culture-mode", "low-key-mode"],
    weatherProfile: { sun: 1, rain: 3, hot: 1, evening: 1 },
    weekdayBoost: { 2: 1, 3: 1, 4: 1, 5: 1, 6: 1 },
    vibeProfile: { evening: 1, culture: 3, lowKey: 2, party: 0 },
  },
  {
    id: "gothic-raval-cultural-connector",
    title: "Gothic to Raval cultural connector",
    summary: "Ett gammalstadsspår som undviker topplistan och istället kopplar ihop rum, hantverk och senare glas.",
    stops: ["placa-sant-felip-neri", "la-manual-alpargatera", "cccb", "bar-marsella"],
    defaultKm: 5,
    preferenceTags: ["kultur", "hidden gems", "shopping", "low-key"],
    optimizerModes: ["culture-mode", "low-key-mode"],
    weatherProfile: { sun: 1, rain: 2, hot: 1, evening: 1 },
    weekdayBoost: { 2: 1, 3: 1, 4: 1, 5: 1, 6: 1 },
    vibeProfile: { evening: 0, culture: 2, lowKey: 3, party: 0 },
  },
  {
    id: "poble-sec-montjuic-evening-arc",
    title: "Poble-sec and Montjuïc evening arc",
    summary: "Montjuïc nedför mot Poble-sec med museum, utsikt och en naturlig kvällsfinal längre ner i staden.",
    stops: ["quimet-quimet", "sala-apolo", "fundacio-joan-miro", "mnac"],
    defaultKm: 6,
    preferenceTags: ["mat", "vin", "kultur", "utsikt", "nattliv", "kväll", "party"],
    optimizerModes: ["sunset-spots", "culture-mode", "evening-mode", "bar-hop", "party-mode"],
    weatherProfile: { sun: 2, rain: 1, hot: -1, evening: 2 },
    weekdayBoost: { 3: 1, 4: 1, 5: 1, 6: 1 },
    vibeProfile: { evening: 3, culture: 2, lowKey: 1, party: 3 },
  },
  {
    id: "encants-to-coast-drift",
    title: "Encants to coast drift",
    summary: "Ett östligt Barcelona-spår där marknad, design och kust fungerar som faktisk rutt i stället för vykort.",
    stops: ["platja-bogatell", "palo-alto-market", "museu-can-framis", "la-cova-fumada", "mercat-encants"],
    defaultKm: 7,
    preferenceTags: ["coast", "market", "second_hand", "shopping", "kultur", "utsikt", "mat", "hidden gems", "lokalt"],
    optimizerModes: ["sunset-spots", "culture-mode", "low-key-mode"],
    weatherProfile: { sun: 3, rain: 1, hot: 0, evening: 1 },
    weekdayBoost: { 0: 1, 5: 1, 6: 2 },
    vibeProfile: { evening: 1, culture: 2, lowKey: 3, party: 0 },
  },
];

const routeAnchorItems = [
  {
    id: "gracia-route-anchor",
    name: "Gràcia",
    kind: "district-group",
    structuralRouteAnchor: true,
    lat: 41.4019,
    lng: 2.1567,
    area: "gracia",
    tags: ["kultur", "mat", "vin", "nattliv", "low-key", "hidden gems", "lokalt"],
    weatherTags: ["all-weather", "evening"],
    anchorWeight: 3.3,
    goodAsStart: 3.2,
    goodAsFinal: 2.7,
    closedWeekdays: [],
    searchTerms: ["gracia", "gràcia", "vila de gracia", "plaça del sol"],
  },
  {
    id: "sant-antoni-route-anchor",
    name: "Sant Antoni",
    kind: "district-group",
    structuralRouteAnchor: true,
    lat: 41.3771,
    lng: 2.1624,
    area: "sant-antoni",
    tags: ["mat", "vin", "nattliv", "kväll", "market", "lokalt", "low-key"],
    weatherTags: ["all-weather", "evening"],
    anchorWeight: 3.4,
    goodAsStart: 3.2,
    goodAsFinal: 2.9,
    closedWeekdays: [],
    searchTerms: ["sant antoni", "parlament", "mercat de sant antoni"],
  },
  {
    id: "born-santa-caterina-route-anchor",
    name: "El Born / Santa Caterina",
    kind: "district-group",
    structuralRouteAnchor: true,
    lat: 41.3856,
    lng: 2.1804,
    area: "born-sant-pere-santa-caterina",
    tags: ["kultur", "kyrkor", "market", "low-key"],
    weatherTags: ["all-weather"],
    anchorWeight: 2.4,
    goodAsStart: 2.4,
    goodAsFinal: 2.2,
    closedWeekdays: [],
    searchTerms: ["el born", "born", "santa caterina", "sant pere", "santa maria del mar"],
  },
  {
    id: "poble-sec-montjuic-route-anchor",
    name: "Poble-sec / Montjuïc",
    kind: "district-group",
    structuralRouteAnchor: true,
    lat: 41.3717,
    lng: 2.1622,
    area: "poble-sec",
    tags: ["mat", "vin", "nattliv", "kväll", "party", "kultur", "utsikt"],
    weatherTags: ["all-weather", "evening", "golden-hour"],
    anchorWeight: 3.5,
    goodAsStart: 2.8,
    goodAsFinal: 3.3,
    closedWeekdays: [],
    searchTerms: ["poble-sec", "poble sec", "montjuic", "montjuïc", "paral-lel", "paral·lel"],
  },
  {
    id: "poblenou-coast-route-anchor",
    name: "Poblenou / Coast",
    kind: "district-group",
    structuralRouteAnchor: true,
    lat: 41.3995,
    lng: 2.2035,
    area: "poblenou",
    tags: ["coast", "utsikt", "mat", "kultur", "market", "hidden gems", "low-key", "lokalt"],
    weatherTags: ["sun", "mild", "golden-hour"],
    anchorWeight: 3.5,
    goodAsStart: 3,
    goodAsFinal: 3.2,
    closedWeekdays: [],
    searchTerms: ["poblenou", "bogatell", "barceloneta", "coast", "beach"],
  },
];

const allItems = [
  ...routeAnchorItems,
  {
    id: "bandinis-barcelona",
    name: "Bandini's",
    kind: "bar",
    lat: 41.376641,
    lng: 2.1609297,
    area: "sant-antoni",
    tags: ["mat", "vin", "cocktail", "nattliv", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bandinis", "bandini", "carrer de manso", "sant antoni", "eixample edge"],
  },
  {
    id: "mercat-sant-antoni",
    name: "Mercat de Sant Antoni",
    kind: "market",
    lat: 41.3786255,
    lng: 2.1620493,
    area: "sant-antoni",
    tags: ["market", "mat", "lokalt", "vintage", "second_hand"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat de sant antoni", "sant antoni market", "mercat sant antoni"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 2, 3, 4, 5, 6],
      weakWeekdays: [0],
      daySensitivity: "medium",
      verifyRecommended: true,
    },
  },
  {
    id: "bar-calders",
    name: "Bar Calders",
    kind: "bar",
    lat: 41.3764788,
    lng: 2.1623937,
    area: "sant-antoni",
    tags: ["vin", "mat", "nattliv", "aperitivo", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bar calders", "calders", "carrer del parlament", "sant antoni"],
  },
  {
    id: "federal-parlament",
    name: "Federal Cafe Parlament",
    kind: "cafe",
    lat: 41.3768982,
    lng: 2.1628879,
    area: "sant-antoni",
    tags: ["mat", "lokalt", "low-key"],
    weatherTags: ["all-weather", "morning"],
    closedWeekdays: [],
    searchTerms: ["federal cafe", "federal parlament", "carrer del parlament", "sant antoni"],
  },
  {
    id: "mercat-encants",
    name: "Mercat dels Encants",
    kind: "market",
    lat: 41.4010304,
    lng: 2.1861738,
    area: "eixample",
    tags: ["market", "second_hand", "vintage", "shopping", "antique", "lokalt"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat dels encants", "els encants", "encants", "fira de bellcaire"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 3, 5, 6],
      weakWeekdays: [0, 2, 4],
      daySensitivity: "high",
      verifyRecommended: true,
    },
  },
  {
    id: "casa-vicens",
    name: "Casa Vicens",
    kind: "museum",
    lat: 41.4035057,
    lng: 2.1506255,
    area: "gracia",
    tags: ["kultur", "klassiker", "arkitektur"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [],
    searchTerms: ["casa vicens", "gaudi", "gracia"],
  },
  {
    id: "cines-verdi",
    name: "Cines Verdi",
    kind: "cinema",
    lat: 41.4040146,
    lng: 2.1568811,
    area: "gracia",
    tags: ["kultur", "nattliv", "low-key"],
    weatherTags: ["rain", "evening"],
    closedWeekdays: [],
    searchTerms: ["cines verdi", "cinema verdi", "verdi", "gracia"],
  },
  {
    id: "bodega-quimet",
    name: "Bodega Quimet",
    kind: "bar",
    lat: 41.3992157,
    lng: 2.1546399,
    area: "gracia",
    tags: ["vin", "mat", "lokalt", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bodega quimet", "quimet gracia", "carrer de vic", "gracia"],
  },
  {
    id: "placa-del-sol",
    name: "Plaça del Sol",
    kind: "square",
    lat: 41.4016246,
    lng: 2.1567108,
    area: "gracia",
    tags: ["lokalt", "nattliv", "low-key", "hidden gems"],
    weatherTags: ["sun", "evening"],
    closedWeekdays: [],
    searchTerms: ["placa del sol", "plaça del sol", "gracia square", "vila de gracia"],
  },
  {
    id: "mercat-santa-caterina",
    name: "Mercat de Santa Caterina",
    kind: "market",
    lat: 41.3861363,
    lng: 2.1785048,
    area: "born-sant-pere-santa-caterina",
    tags: ["market", "mat", "lokalt", "kultur"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat de santa caterina", "santa caterina market", "mercat santa caterina"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 2, 3, 4, 5, 6],
      weakWeekdays: [0],
      daySensitivity: "medium",
      verifyRecommended: true,
    },
  },
  {
    id: "santa-maria-del-mar",
    name: "Santa Maria del Mar",
    kind: "church",
    lat: 41.3837802,
    lng: 2.1820062,
    area: "born-sant-pere-santa-caterina",
    tags: ["kultur", "kyrkor", "klassiker"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [],
    searchTerms: ["santa maria del mar", "basilica santa maria del mar", "el born"],
  },
  {
    id: "museu-picasso",
    name: "Museu Picasso",
    kind: "museum",
    lat: 41.3851039,
    lng: 2.1812015,
    area: "born-sant-pere-santa-caterina",
    tags: ["kultur", "klassiker", "museum"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [1],
    searchTerms: ["museu picasso", "picasso museum", "museo picasso", "el born"],
  },
  {
    id: "bar-brutal",
    name: "Bar Brutal",
    kind: "bar",
    lat: 41.3852677,
    lng: 2.1805362,
    area: "born-sant-pere-santa-caterina",
    tags: ["vin", "mat", "nattliv", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bar brutal", "brutal barcelona", "carrer de la princesa", "el born"],
  },
  {
    id: "placa-sant-felip-neri",
    name: "Plaça de Sant Felip Neri",
    kind: "square",
    lat: 41.3833846,
    lng: 2.1750998,
    area: "gothic",
    tags: ["kultur", "hidden gems", "low-key"],
    weatherTags: ["sun", "mild"],
    closedWeekdays: [],
    searchTerms: ["placa sant felip neri", "plaça de sant felip neri", "gothic quarter"],
  },
  {
    id: "la-manual-alpargatera",
    name: "La Manual Alpargatera",
    kind: "shop",
    lat: 41.3815528,
    lng: 2.1761225,
    area: "gothic",
    tags: ["shopping", "kultur", "klassiker", "lokalt"],
    weatherTags: ["all-weather"],
    closedWeekdays: [],
    searchTerms: ["la manual alpargatera", "alpargatera", "espadrilles", "gothic quarter"],
    availability: {
      kind: "shop",
      daySensitivity: "low",
      verifyRecommended: true,
    },
  },
  {
    id: "la-plata",
    name: "La Plata",
    kind: "bar",
    lat: 41.3804049,
    lng: 2.1805946,
    area: "gothic",
    tags: ["mat", "vin", "lokalt", "klassiker"],
    weatherTags: ["all-weather"],
    closedWeekdays: [],
    searchTerms: ["la plata", "carrer de la merce", "gothic quarter"],
  },
  {
    id: "cccb",
    name: "CCCB",
    kind: "museum",
    lat: 41.383693,
    lng: 2.1662438,
    area: "raval",
    tags: ["kultur", "museum", "hidden gems"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [1],
    searchTerms: ["cccb", "centre de cultura contemporania", "montalegre", "raval"],
  },
  {
    id: "bar-marsella",
    name: "Bar Marsella",
    kind: "bar",
    lat: 41.3782418,
    lng: 2.1712432,
    area: "raval",
    tags: ["nattliv", "cocktail", "klassiker", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["bar marsella", "marsella", "absinthe", "raval"],
  },
  {
    id: "quimet-quimet",
    name: "Quimet & Quimet",
    kind: "bar",
    lat: 41.374222,
    lng: 2.1657389,
    area: "poble-sec",
    tags: ["mat", "vin", "klassiker", "low-key"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["quimet quimet", "quimet & quimet", "poble-sec", "poeta cabanyes"],
  },
  {
    id: "sala-apolo",
    name: "Sala Apolo",
    kind: "music",
    lat: 41.3743908,
    lng: 2.1695606,
    area: "poble-sec",
    tags: ["nattliv", "party", "kultur", "music"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["sala apolo", "apolo", "nou de la rambla", "poble-sec"],
  },
  {
    id: "fundacio-joan-miro",
    name: "Fundació Joan Miró",
    kind: "museum",
    lat: 41.3686445,
    lng: 2.1600839,
    area: "montjuic",
    tags: ["kultur", "museum", "utsikt", "klassiker"],
    weatherTags: ["rain", "hot", "sun"],
    closedWeekdays: [1],
    searchTerms: ["fundacio joan miro", "fundació joan miró", "joan miro", "montjuic"],
  },
  {
    id: "mnac",
    name: "MNAC",
    kind: "museum",
    lat: 41.3684015,
    lng: 2.1534231,
    area: "montjuic",
    tags: ["kultur", "museum", "utsikt", "klassiker"],
    weatherTags: ["rain", "hot", "golden-hour"],
    closedWeekdays: [1],
    searchTerms: ["mnac", "museu nacional", "palau nacional", "montjuic"],
  },
  {
    id: "museu-can-framis",
    name: "Museu Can Framis",
    kind: "museum",
    lat: 41.4027616,
    lng: 2.1944335,
    area: "poblenou",
    tags: ["kultur", "museum", "hidden gems", "low-key"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [1],
    searchTerms: ["museu can framis", "can framis", "poblenou"],
  },
  {
    id: "palo-alto-market",
    name: "Palo Alto Market",
    kind: "event_market",
    lat: 41.4043377,
    lng: 2.2105052,
    area: "poblenou",
    tags: ["market", "event_market", "mat", "shopping", "kultur", "hidden gems"],
    weatherTags: ["all-weather", "weekend"],
    closedWeekdays: [1, 2, 3, 4, 5],
    searchTerms: ["palo alto market", "palo alto", "poblenou", "pellaires"],
    availability: {
      kind: "event_market",
      strongWeekdays: [0, 6],
      weakWeekdays: [1, 2, 3, 4, 5],
      daySensitivity: "high",
      verifyRecommended: true,
    },
  },
  {
    id: "platja-bogatell",
    name: "Platja del Bogatell",
    kind: "beach",
    lat: 41.3939544,
    lng: 2.2066734,
    area: "poblenou",
    tags: ["coast", "utsikt", "low-key", "lokalt"],
    weatherTags: ["sun", "mild", "golden-hour"],
    closedWeekdays: [],
    searchTerms: ["platja del bogatell", "bogatell beach", "beach", "poblenou"],
  },
  {
    id: "la-cova-fumada",
    name: "La Cova Fumada",
    kind: "restaurant",
    lat: 41.3792983,
    lng: 2.1891943,
    area: "barceloneta",
    tags: ["mat", "lokalt", "klassiker", "hidden gems"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["la cova fumada", "cova fumada", "barceloneta", "baluard"],
  },
  {
    id: "sala-beckett",
    name: "Sala Beckett",
    kind: "theatre",
    lat: 41.4045826,
    lng: 2.1996057,
    area: "poblenou",
    tags: ["kultur", "nattliv", "low-key", "hidden gems"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["sala beckett", "beckett", "carrer de batista", "poblenou"],
  },
  {
    id: "rambla-del-poblenou",
    name: "Rambla del Poblenou",
    kind: "promenade",
    lat: 41.4066072,
    lng: 2.1938886,
    area: "poblenou",
    tags: ["lokalt", "low-key", "coast", "mat"],
    weatherTags: ["sun", "mild", "evening"],
    closedWeekdays: [],
    searchTerms: ["rambla del poblenou", "rambla poblenou", "poblenou rambla", "poblenou"],
  },
  {
    id: "platja-mar-bella",
    name: "Platja de la Mar Bella",
    kind: "beach",
    lat: 41.3980426,
    lng: 2.2122443,
    area: "poblenou",
    tags: ["coast", "utsikt", "low-key", "lokalt"],
    weatherTags: ["sun", "mild", "golden-hour"],
    closedWeekdays: [],
    searchTerms: ["platja de la mar bella", "mar bella", "mar bella beach", "poblenou beach"],
  },
  {
    id: "parc-centre-poblenou",
    name: "Parc del Centre del Poblenou",
    kind: "park",
    lat: 41.4079163,
    lng: 2.2013182,
    area: "poblenou",
    tags: ["kultur", "hidden gems", "low-key", "lokalt"],
    weatherTags: ["sun", "mild"],
    closedWeekdays: [],
    searchTerms: ["parc del centre del poblenou", "parc centre poblenou", "avinguda diagonal 130", "poblenou park"],
  },
  {
    id: "mercat-poblenou",
    name: "Mercat de Poblenou",
    kind: "market",
    lat: 41.4008487,
    lng: 2.2052472,
    area: "poblenou",
    tags: ["market", "mat", "lokalt", "shopping"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat de poblenou", "mercat del poblenou", "poblenou market", "poblenou"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 2, 3, 4, 5, 6],
      weakWeekdays: [0],
      daySensitivity: "medium",
      verifyRecommended: true,
    },
  },
  {
    id: "mercat-barceloneta",
    name: "Mercat de la Barceloneta",
    kind: "market",
    lat: 41.3803769,
    lng: 2.1891867,
    area: "barceloneta",
    tags: ["market", "mat", "lokalt", "coast"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat de la barceloneta", "mercat barceloneta", "barceloneta market", "barceloneta"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 2, 3, 4, 5, 6],
      weakWeekdays: [0],
      daySensitivity: "medium",
      verifyRecommended: true,
    },
  },
  {
    id: "platja-barceloneta",
    name: "Platja de la Barceloneta",
    kind: "beach",
    lat: 41.3793285,
    lng: 2.192971,
    area: "barceloneta",
    tags: ["coast", "utsikt", "lokalt", "low-key"],
    weatherTags: ["sun", "mild", "golden-hour"],
    closedWeekdays: [],
    searchTerms: ["platja de la barceloneta", "barceloneta beach", "barceloneta", "beach"],
  },
  {
    id: "museu-historia-catalunya",
    name: "Museu d'Història de Catalunya",
    kind: "museum",
    lat: 41.3806173,
    lng: 2.1859682,
    area: "barceloneta",
    tags: ["kultur", "klassiker", "museum", "coast"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [1],
    searchTerms: ["museu historia de catalunya", "museu d'historia de catalunya", "mhcat", "placa de pau vila", "barceloneta"],
  },
  {
    id: "mercat-llibertat",
    name: "Mercat de la Llibertat",
    kind: "market",
    lat: 41.3998626,
    lng: 2.1534854,
    area: "gracia",
    tags: ["market", "mat", "lokalt", "shopping"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat de la llibertat", "mercat llibertat", "llibertat market", "gracia"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 2, 3, 4, 5, 6],
      weakWeekdays: [0],
      daySensitivity: "medium",
      verifyRecommended: true,
    },
  },
  {
    id: "heliogabal",
    name: "Heliogàbal",
    kind: "bar",
    lat: 41.4035629,
    lng: 2.1603403,
    area: "gracia",
    tags: ["nattliv", "music", "lokalt", "hidden gems", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["heliogabal", "heliogàbal", "heliogabal gracia", "ramon y cajal", "gracia"],
  },
  {
    id: "teatreneu",
    name: "Teatreneu",
    kind: "theatre",
    lat: 41.4032396,
    lng: 2.1585587,
    area: "gracia",
    tags: ["kultur", "nattliv", "low-key", "lokalt"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["teatreneu", "carrer de terol", "gracia theatre", "gracia"],
  },
  {
    id: "placa-virreina",
    name: "Plaça de la Virreina",
    kind: "square",
    lat: 41.4049409,
    lng: 2.157234,
    area: "gracia",
    tags: ["lokalt", "low-key", "hidden gems", "nattliv"],
    weatherTags: ["sun", "mild", "evening"],
    closedWeekdays: [],
    searchTerms: ["placa de la virreina", "plaça de la virreina", "placa virreina", "virreina", "gracia"],
  },
  {
    id: "placa-vila-gracia",
    name: "Plaça de la Vila de Gràcia",
    kind: "square",
    lat: 41.4001993,
    lng: 2.1576098,
    area: "gracia",
    tags: ["lokalt", "nattliv", "low-key", "klassiker"],
    weatherTags: ["sun", "mild", "evening"],
    closedWeekdays: [],
    searchTerms: ["placa de la vila de gracia", "plaça de la vila de gràcia", "placa vila gracia", "rius i taulet", "gracia square"],
  },
  {
    id: "biblioteca-jaume-fuster",
    name: "Biblioteca Jaume Fuster",
    kind: "library",
    lat: 41.4074746,
    lng: 2.1492978,
    area: "gracia",
    tags: ["kultur", "low-key", "lokalt"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [],
    searchTerms: ["biblioteca jaume fuster", "jaume fuster", "placa de lesseps", "gracia library"],
  },
  {
    id: "placa-diamant",
    name: "Plaça del Diamant",
    kind: "square",
    lat: 41.4040651,
    lng: 2.1558545,
    area: "gracia",
    tags: ["lokalt", "low-key", "hidden gems", "kultur"],
    weatherTags: ["sun", "mild", "evening"],
    closedWeekdays: [],
    searchTerms: ["placa del diamant", "plaça del diamant", "placa diamant", "diamant", "gracia"],
  },
  {
    id: "caixaforum-barcelona",
    name: "CaixaForum Barcelona",
    kind: "museum",
    lat: 41.3714827,
    lng: 2.1493553,
    area: "montjuic",
    tags: ["kultur", "museum", "klassiker"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [],
    searchTerms: ["caixaforum barcelona", "caixaforum", "fabrica casaramona", "montjuic"],
  },
  {
    id: "teatre-lliure",
    name: "Teatre Lliure",
    kind: "theatre",
    lat: 41.3706436,
    lng: 2.15714,
    area: "poble-sec",
    tags: ["kultur", "nattliv", "low-key", "lokalt"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["teatre lliure", "mercat de les flors", "passeig de santa madrona", "poble-sec"],
  },
  {
    id: "castell-montjuic",
    name: "Castell de Montjuïc",
    kind: "castle",
    lat: 41.3627047,
    lng: 2.1647847,
    area: "montjuic",
    tags: ["kultur", "klassiker", "utsikt"],
    weatherTags: ["sun", "mild", "golden-hour"],
    closedWeekdays: [],
    searchTerms: ["castell de montjuic", "castell de montjuïc", "castell montjuic", "montjuic castle", "montjuic"],
  },
  {
    id: "jardins-laribal",
    name: "Jardins de Laribal",
    kind: "park",
    lat: 41.3673581,
    lng: 2.1579456,
    area: "montjuic",
    tags: ["utsikt", "low-key", "hidden gems", "kultur"],
    weatherTags: ["sun", "mild", "golden-hour"],
    closedWeekdays: [],
    searchTerms: ["jardins de laribal", "laribal gardens", "montjuic gardens", "montjuic"],
  },
  {
    id: "poble-espanyol",
    name: "Poble Espanyol",
    kind: "museum",
    lat: 41.3686484,
    lng: 2.1485021,
    area: "montjuic",
    tags: ["kultur", "klassiker", "mat", "shopping"],
    weatherTags: ["all-weather", "sun"],
    closedWeekdays: [],
    searchTerms: ["poble espanyol", "pueblo espanol", "avinguda de francesc ferrer i guardia", "montjuic"],
  },
  {
    id: "la-federica",
    name: "La Federica",
    kind: "bar",
    lat: 41.3744951,
    lng: 2.1667538,
    area: "poble-sec",
    tags: ["nattliv", "cocktail", "vin", "lokalt", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [1, 2],
    searchTerms: ["la federica", "carrer de salva", "salva 3", "poble-sec"],
  },
  {
    id: "mercat-ninot",
    name: "Mercat del Ninot",
    kind: "market",
    lat: 41.3880578,
    lng: 2.1541155,
    area: "eixample",
    tags: ["market", "mat", "lokalt", "shopping"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["mercat del ninot", "mercat ninot", "ninot market", "eixample"],
    availability: {
      kind: "market",
      strongWeekdays: [1, 2, 3, 4, 5, 6],
      weakWeekdays: [0],
      daySensitivity: "medium",
      verifyRecommended: true,
    },
  },
  {
    id: "llibreria-finestres",
    name: "Llibreria Finestres",
    kind: "shop",
    lat: 41.3889711,
    lng: 2.1649547,
    area: "eixample",
    tags: ["shopping", "kultur", "low-key", "lokalt"],
    weatherTags: ["all-weather", "rain"],
    closedWeekdays: [0],
    searchTerms: ["llibreria finestres", "finestres", "diputacio 249", "eixample"],
  },
  {
    id: "museu-tapies",
    name: "Museu Tàpies",
    kind: "museum",
    lat: 41.3916216,
    lng: 2.1636636,
    area: "eixample",
    tags: ["kultur", "museum", "klassiker"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [1],
    searchTerms: ["museu tapies", "museu tàpies", "fundacio antoni tapies", "fundació antoni tàpies", "antoni tapies", "arago 255", "eixample"],
  },
  {
    id: "dry-martini",
    name: "Dry Martini",
    kind: "bar",
    lat: 41.3927442,
    lng: 2.1539985,
    area: "eixample",
    tags: ["cocktail", "nattliv", "vin", "klassiker"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["dry martini", "aribau 162", "eixample cocktail"],
  },
  {
    id: "fabrica-moritz-barcelona",
    name: "Fàbrica Moritz Barcelona",
    kind: "bar",
    lat: 41.3825668,
    lng: 2.1633965,
    area: "sant-antoni",
    tags: ["mat", "öl", "nattliv", "klassiker"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["fabrica moritz barcelona", "fàbrica moritz barcelona", "moritz", "ronda sant antoni", "sant antoni"],
  },
  {
    id: "la-central-mallorca",
    name: "La Central",
    kind: "shop",
    lat: 41.3920495,
    lng: 2.1600012,
    area: "eixample",
    tags: ["shopping", "kultur", "low-key", "lokalt"],
    weatherTags: ["all-weather", "rain"],
    closedWeekdays: [0],
    searchTerms: ["la central", "la central mallorca", "mallorca 237", "eixample bookshop"],
  },
  {
    id: "garage-beer-co",
    name: "Garage Beer Co",
    kind: "bar",
    lat: 41.3870022,
    lng: 2.1600957,
    area: "eixample",
    tags: ["öl", "nattliv", "lokalt", "low-key"],
    weatherTags: ["all-weather", "evening"],
    closedWeekdays: [],
    searchTerms: ["garage beer co", "garage beer", "consell de cent 261", "eixample"],
  },
  {
    id: "filmoteca-catalunya",
    name: "Filmoteca de Catalunya",
    kind: "cinema",
    lat: 41.378533,
    lng: 2.1709403,
    area: "raval",
    tags: ["kultur", "low-key", "hidden gems"],
    weatherTags: ["rain", "evening"],
    closedWeekdays: [],
    searchTerms: ["filmoteca de catalunya", "filmoteca", "raval cinema", "raval"],
  },
  {
    id: "born-museu-historia-barcelona",
    name: "El Born: Museu d'Història de Barcelona",
    kind: "museum",
    lat: 41.3858311,
    lng: 2.1838008,
    area: "born-sant-pere-santa-caterina",
    tags: ["kultur", "klassiker", "hidden gems"],
    weatherTags: ["rain", "hot"],
    closedWeekdays: [1],
    searchTerms: ["born ccm", "el born centre de cultura i memoria", "el born centre de cultura i memòria", "mercat del born", "born museum", "el born"],
  },
];

const provenanceById = {
  "gracia-route-anchor": {
    source_type: "citypack_structural_model",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Structural route anchor for the Gracia neighborhood model; not a venue or curated place.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["food_drink", "culture", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["start", "final", "neighborhood_anchor"],
    classification: "route_anchor",
    needs_human_verification: false,
    source_note: "Derived from the Barcelona neighborhood model added in PR #47.",
  },
  "sant-antoni-route-anchor": {
    source_type: "citypack_structural_model",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Structural route anchor for Sant Antoni and Parlament food/bar flows; not a venue or curated place.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "nightlife", "market", "low_key"],
    time_fit: ["morning", "afternoon", "evening"],
    route_role: ["start", "final", "neighborhood_anchor"],
    classification: "route_anchor",
    needs_human_verification: false,
    source_note: "Derived from the Barcelona neighborhood model added in PR #47.",
  },
  "born-santa-caterina-route-anchor": {
    source_type: "citypack_structural_model",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Structural route anchor for Born, Sant Pere, and Santa Caterina culture/market flows; not a venue or curated place.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["culture", "food_drink", "market", "low_key"],
    time_fit: ["morning", "afternoon", "evening"],
    route_role: ["start", "final", "neighborhood_anchor"],
    classification: "route_anchor",
    needs_human_verification: false,
    source_note: "Derived from the Barcelona neighborhood model added in PR #47.",
  },
  "poble-sec-montjuic-route-anchor": {
    source_type: "citypack_structural_model",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Structural route anchor for Poble-sec and Montjuic evening/view flows; not a venue or curated place.",
    area: "poble-sec",
    macro: "montjuic-southwest",
    tags_intents: ["food_drink", "nightlife", "culture", "views"],
    time_fit: ["afternoon", "evening", "late"],
    route_role: ["start", "final", "neighborhood_anchor"],
    classification: "route_anchor",
    needs_human_verification: false,
    source_note: "Derived from the Barcelona neighborhood model added in PR #47.",
  },
  "poblenou-coast-route-anchor": {
    source_type: "citypack_structural_model",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Structural route anchor for Poblenou, Barceloneta, and coast/east flows; not a venue or curated place.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["food_drink", "culture", "views", "coast", "low_key"],
    time_fit: ["morning", "afternoon", "golden_hour"],
    route_role: ["start", "final", "neighborhood_anchor"],
    classification: "route_anchor",
    needs_human_verification: false,
    source_note: "Derived from the Barcelona neighborhood model added in PR #47.",
  },
  "bandinis-barcelona": {
    source_url: "https://www.bandinisbarcelona.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Normal beta seed from issue #45; useful Sant Antoni food/bar anchor near the Eixample edge.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["food_anchor", "bar_anchor", "middle"],
    classification: "beta_seed",
    needs_human_verification: false,
    source_note: "Issue #45 identifies Bandini's as a beta seed; Nominatim confirmed Carrer de Manso 42 coordinates.",
  },
  "mercat-sant-antoni": {
    source_type: "osm_structured_data",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Market anchor for Sant Antoni with food and second-hand/vintage route value.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "second_hand", "market"],
    time_fit: ["morning", "lunch", "afternoon"],
    route_role: ["start", "market", "food_anchor"],
    classification: "local_anchor",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed market address and coordinates during catalog pass.",
  },
  "bar-calders": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Sant Antoni bar/food connector on Parlament, useful for soft evening routes.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["bar_anchor", "middle", "final"],
    classification: "local_anchor",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed place/address; source should be human-checked before curated launch.",
  },
  "federal-parlament": {
    source_url: "https://www.federalcafe.es/",
    source_type: "official_site",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Morning/lunch anchor on Parlament that helps Sant Antoni routes start gently.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "local_anchor"],
    time_fit: ["morning", "lunch"],
    route_role: ["start", "food_anchor"],
    classification: "practical_connector",
    needs_human_verification: true,
  },
  "mercat-encants": {
    source_url: "https://encants.cat/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Large market/second-hand anchor that can test vintage and market intents without tourist framing.",
    area: "eixample",
    macro: "central-grid",
    tags_intents: ["second_hand", "market", "shopping"],
    time_fit: ["morning", "afternoon"],
    route_role: ["market", "connector", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "casa-vicens": {
    source_url: "https://casavicens.org/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Cultural Gràcia anchor that adds architecture without defaulting to the busiest old-town loop.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["culture", "classic"],
    time_fit: ["morning", "afternoon"],
    route_role: ["start", "culture_anchor"],
    classification: "classic",
    needs_human_verification: false,
  },
  "cines-verdi": {
    source_url: "https://barcelona.cines-verdi.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Gràcia cultural/evening anchor that supports repeat-visitor and rainy-day routes.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["culture", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["middle", "final"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "bodega-quimet": {
    source_url: "https://www.bodegaquimet.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Compact Gràcia bar/food anchor for local evening drift.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["food_drink", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["bar_anchor", "final"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "placa-del-sol": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Useful Gràcia connector and evening square, especially for routes that should drift rather than checklist.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["local_anchor", "nightlife", "hidden_gems"],
    time_fit: ["afternoon", "evening"],
    route_role: ["connector", "middle"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed square coordinates; local rhythm should be human-verified.",
  },
  "mercat-santa-caterina": {
    source_type: "osm_structured_data",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Market anchor for Born/Sant Pere/Santa Caterina routes with food and old-town connector value.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["food_drink", "market", "culture"],
    time_fit: ["morning", "lunch"],
    route_role: ["market", "food_anchor", "start"],
    classification: "local_anchor",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed market address and coordinates during catalog pass.",
  },
  "santa-maria-del-mar": {
    source_url: "https://www.santamariadelmarbarcelona.org/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Culture anchor in Born that can carry church/culture intent without making a full tourist loop.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["culture"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "museu-picasso": {
    source_url: "https://museupicassobcn.cat/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Major museum anchor that helps test culture routes in Born without needing route seeds yet.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["culture"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "bar-brutal": {
    source_url: "https://www.brutalbarcelona.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Natural-wine/food anchor that supports evening routes in Born/Sant Pere.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["food_drink", "nightlife"],
    time_fit: ["evening"],
    route_role: ["food_anchor", "bar_anchor", "final"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "placa-sant-felip-neri": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Quiet Gothic connector with cultural weight, useful only when it improves old-town flow.",
    area: "gothic",
    macro: "old-town",
    tags_intents: ["culture", "hidden_gems", "low_key"],
    time_fit: ["morning", "afternoon"],
    route_role: ["connector", "culture_anchor"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed square coordinates; inclusion should remain route-useful, not checklist-driven.",
  },
  "la-manual-alpargatera": {
    source_url: "https://lamanual.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Gothic shop/craft anchor that adds local retail texture without fake hidden-gem framing.",
    area: "gothic",
    macro: "old-town",
    tags_intents: ["shopping", "culture"],
    time_fit: ["morning", "afternoon"],
    route_role: ["middle", "connector"],
    classification: "classic",
    needs_human_verification: false,
  },
  "la-plata": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Small Gothic food/bar anchor that can make old-town routes feel less generic.",
    area: "gothic",
    macro: "old-town",
    tags_intents: ["food_drink", "local_anchor"],
    time_fit: ["lunch", "evening"],
    route_role: ["food_anchor", "bar_anchor"],
    classification: "classic",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed place/address; source should be human-checked before public beta.",
  },
  cccb: {
    source_url: "https://www.cccb.org/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Raval culture anchor with strong rainy-day and repeat-visitor value.",
    area: "raval",
    macro: "old-town",
    tags_intents: ["culture"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "start", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "bar-marsella": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Historic Raval night anchor, useful with caution for late routes.",
    area: "raval",
    macro: "old-town",
    tags_intents: ["nightlife", "cocktail"],
    time_fit: ["evening", "late"],
    route_role: ["bar_anchor", "final"],
    classification: "classic",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed place/address; current operations should be human-verified.",
  },
  "quimet-quimet": {
    source_url: "https://quimetiquimet.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Poble-sec food/wine anchor that links theater, Montjuïc edge, and evening routes.",
    area: "poble-sec",
    macro: "montjuic-southwest",
    tags_intents: ["food_drink", "classic"],
    time_fit: ["lunch", "evening"],
    route_role: ["food_anchor", "bar_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "sala-apolo": {
    source_url: "https://www.sala-apolo.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Poble-sec nightlife/culture anchor for later event-aware routes.",
    area: "poble-sec",
    macro: "montjuic-southwest",
    tags_intents: ["nightlife", "culture"],
    time_fit: ["evening", "late"],
    route_role: ["final", "nightlife_place"],
    classification: "nightlife_place",
    needs_human_verification: false,
  },
  "fundacio-joan-miro": {
    source_url: "https://www.fmirobcn.org/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Montjuïc culture anchor that supports park/view arcs rather than isolated museum stops.",
    area: "montjuic",
    macro: "montjuic-southwest",
    tags_intents: ["culture", "views"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "view", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  mnac: {
    source_url: "https://www.museunacional.cat/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Culture/view anchor for Montjuïc routes and golden-hour route endings.",
    area: "montjuic",
    macro: "montjuic-southwest",
    tags_intents: ["culture", "views"],
    time_fit: ["morning", "afternoon", "golden_hour"],
    route_role: ["culture_anchor", "view", "final"],
    classification: "classic",
    needs_human_verification: false,
  },
  "museu-can-framis": {
    source_url: "https://www.fundaciovilacasas.com/en/museum/can-framis",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Poblenou culture anchor that helps routes avoid only beach/postcard logic.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["culture", "hidden_gems"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "palo-alto-market": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Event-market anchor for Poblenou design/food rhythm; high date sensitivity.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["market", "food_drink", "shopping", "culture"],
    time_fit: ["weekend", "afternoon"],
    route_role: ["market", "middle"],
    classification: "event_market",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed location; live/event schedule must be verified before user-facing route use.",
  },
  "platja-bogatell": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Coast connector that helps model beach flow as part of a day rather than as postcard content.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["views", "coast", "low_key"],
    time_fit: ["morning", "afternoon", "golden_hour"],
    route_role: ["connector", "view", "final"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed beach coordinates; seasonal fit needs later review.",
  },
  "la-cova-fumada": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Barceloneta food anchor with coast-neighborhood route value.",
    area: "barceloneta",
    macro: "coast-east",
    tags_intents: ["food_drink", "local_anchor"],
    time_fit: ["lunch", "afternoon"],
    route_role: ["food_anchor", "middle"],
    classification: "classic",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Nominatim confirmed place/address; current hours should be human-verified.",
  },
  "sala-beckett": {
    source_url: "https://www.salabeckett.cat/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Poblenou culture anchor that gives east-side routes a real evening room rather than only beach drift.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["culture", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["culture_anchor", "middle", "final"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "rambla-del-poblenou": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Public east-side connector that helps Poblenou routes feel like neighborhood drift rather than isolated venue jumps.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["coast", "food_drink", "low_key"],
    time_fit: ["morning", "afternoon", "evening"],
    route_role: ["connector", "middle"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Overpass confirmed the Rambla del Poblenou corridor and central coordinates.",
  },
  "platja-mar-bella": {
    source_url: "https://www.barcelonaturisme.com/wv3/en/page/1117/mar-bella-beach.html",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Coast anchor that lets east-facing days actually reach the sea without collapsing back into old town.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["coast", "views", "low_key"],
    time_fit: ["morning", "afternoon", "golden_hour"],
    route_role: ["view", "connector", "final"],
    classification: "practical_connector",
    needs_human_verification: false,
  },
  "parc-centre-poblenou": {
    source_url: "https://www.barcelona.cat/ca/que-pots-fer-a-bcn/parcs-i-jardins/parc-del-centre-del-poblenou_99400201005.html",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "A calm design-forward Poblenou connector that can soften coast and culture routes without fake hidden-gem framing.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["culture", "low_key", "hidden_gems"],
    time_fit: ["morning", "afternoon"],
    route_role: ["connector", "middle"],
    classification: "practical_connector",
    needs_human_verification: false,
  },
  "mercat-poblenou": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Market anchor that gives Poblenou daytime routes local food gravity instead of only design or beach stops.",
    area: "poblenou",
    macro: "coast-east",
    tags_intents: ["market", "food_drink", "shopping"],
    time_fit: ["morning", "lunch", "afternoon"],
    route_role: ["market", "food_anchor", "start"],
    classification: "local_anchor",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Overpass confirmed the Mercat de Poblenou building and central coordinates.",
  },
  "mercat-barceloneta": {
    source_url: "http://www.mercatdelabarceloneta.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Barceloneta market anchor that gives the coast area a usable daytime stop beyond postcard beach logic.",
    area: "barceloneta",
    macro: "coast-east",
    tags_intents: ["market", "food_drink", "coast"],
    time_fit: ["morning", "lunch", "afternoon"],
    route_role: ["market", "food_anchor", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "platja-barceloneta": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Direct coast connector for Barceloneta routes when the day should actually touch the waterfront.",
    area: "barceloneta",
    macro: "coast-east",
    tags_intents: ["coast", "views", "low_key"],
    time_fit: ["morning", "afternoon", "golden_hour"],
    route_role: ["connector", "view", "final"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "Nominatim confirmed the Barceloneta beach feature and central coordinates.",
  },
  "museu-historia-catalunya": {
    source_url: "https://mhcat.cat",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Barceloneta culture anchor that helps coast routes carry real indoor weight when weather or pacing needs it.",
    area: "barceloneta",
    macro: "coast-east",
    tags_intents: ["culture", "classic", "coast"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "mercat-llibertat": {
    source_url: "https://mercatllibertat.cat",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "A real Gracia market anchor so neighborhood routes can start with food rhythm instead of immediately drifting out of area.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["market", "food_drink", "shopping"],
    time_fit: ["morning", "lunch", "afternoon"],
    route_role: ["market", "food_anchor", "start"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  heliogabal: {
    source_url: "https://www.heliogabal.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Compact Gracia night/culture anchor that strengthens local evening routes without turning them back toward old town.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["nightlife", "culture", "hidden_gems"],
    time_fit: ["afternoon", "evening", "late"],
    route_role: ["bar_anchor", "nightlife_place", "final"],
    classification: "nightlife_place",
    needs_human_verification: false,
  },
  teatreneu: {
    source_url: "https://www.teatreneu.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Gracia culture/evening anchor that adds local room-based culture rather than only plazas and bars.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["culture", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["culture_anchor", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "placa-virreina": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Useful Gracia connector square for routes that should drift through the neighborhood instead of checklisting venues.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["local_anchor", "low_key", "hidden_gems"],
    time_fit: ["afternoon", "evening"],
    route_role: ["connector", "middle"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Overpass confirmed the square geometry and central coordinates.",
  },
  "placa-vila-gracia": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Central Gracia meeting-point connector that helps local start hints stay local longer.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["local_anchor", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["connector", "middle"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Overpass confirmed the square geometry and central coordinates.",
  },
  "biblioteca-jaume-fuster": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "A Gracia culture connector that broadens daytime routes with a calmer local indoor stop.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["culture", "low_key"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Overpass confirmed the library building and central coordinates.",
  },
  "placa-diamant": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Another Gracia connector that helps the neighborhood carry slower routes without always reusing the same plaza.",
    area: "gracia",
    macro: "northwest-local",
    tags_intents: ["local_anchor", "hidden_gems", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["connector", "middle"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Overpass confirmed the square geometry and central coordinates.",
  },
  "caixaforum-barcelona": {
    source_url: "https://caixaforum.es/barcelona",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Reliable Montjuic culture anchor that makes southwest routes sturdier in mixed-weather or museum-leaning scenarios.",
    area: "montjuic",
    macro: "montjuic-southwest",
    tags_intents: ["culture", "classic"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "start", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "teatre-lliure": {
    source_url: "https://teatrelliure.com/ca",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Poble-sec culture anchor that gives the southwest a more lived-in evening/culture layer.",
    area: "poble-sec",
    macro: "montjuic-southwest",
    tags_intents: ["culture", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening"],
    route_role: ["culture_anchor", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "castell-montjuic": {
    source_url: "https://ajuntament.barcelona.cat/castelldemontjuic/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "A classic Montjuic view/culture anchor that can genuinely carry the high point of a southwest day.",
    area: "montjuic",
    macro: "montjuic-southwest",
    tags_intents: ["culture", "views", "classic"],
    time_fit: ["morning", "afternoon", "golden_hour"],
    route_role: ["culture_anchor", "view", "final"],
    classification: "classic",
    needs_human_verification: false,
  },
  "jardins-laribal": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Montjuic park connector that makes southwest routes feel like a real hillside flow instead of a museum hop.",
    area: "montjuic",
    macro: "montjuic-southwest",
    tags_intents: ["views", "culture", "low_key"],
    time_fit: ["morning", "afternoon", "golden_hour"],
    route_role: ["connector", "view", "middle"],
    classification: "practical_connector",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Overpass confirmed the Jardins de Laribal reference point.",
  },
  "poble-espanyol": {
    source_url: "https://www.poble-espanyol.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "A classic Montjuic culture anchor that gives the southwest more stop density without borrowing old-town energy.",
    area: "montjuic",
    macro: "montjuic-southwest",
    tags_intents: ["culture", "classic", "food_drink", "shopping"],
    time_fit: ["morning", "afternoon", "evening"],
    route_role: ["culture_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "la-federica": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Poble-sec bar anchor that strengthens later southwest routes without overusing the same existing nightlife stops.",
    area: "poble-sec",
    macro: "montjuic-southwest",
    tags_intents: ["nightlife", "food_drink", "low_key"],
    time_fit: ["evening", "late"],
    route_role: ["bar_anchor", "final"],
    classification: "nightlife_place",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Overpass confirmed the venue and current opening-hours pattern.",
  },
  "mercat-ninot": {
    source_type: "osm_structured_data",
    confidence: "medium",
    last_checked: LAST_CHECKED,
    why_included: "Eixample market anchor that widens central-grid daytime routes without pushing every food plan back into Sant Antoni proper.",
    area: "eixample",
    macro: "central-grid",
    tags_intents: ["market", "food_drink", "shopping"],
    time_fit: ["morning", "lunch", "afternoon"],
    route_role: ["market", "food_anchor", "start"],
    classification: "local_anchor",
    needs_human_verification: true,
    source_note: "OpenStreetMap/Overpass confirmed the Mercat del Ninot building and central coordinates.",
  },
  "llibreria-finestres": {
    source_url: "https://www.llibreriafinestres.com/ca/home-catala/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Quiet Eixample culture/shop anchor that adds repeat-visitor usefulness and a softer indoor stop.",
    area: "eixample",
    macro: "central-grid",
    tags_intents: ["shopping", "culture", "low_key"],
    time_fit: ["morning", "afternoon"],
    route_role: ["shop_anchor", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "museu-tapies": {
    source_url: "https://museutapies.org/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Current official Tàpies site confirms the renamed museum and gives Eixample a real modern-art culture anchor.",
    area: "eixample",
    macro: "central-grid",
    tags_intents: ["culture", "classic"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "dry-martini": {
    source_url: "https://www.drymartiniorg.com/locales/dry-martini-v2/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Classic cocktail anchor that helps Eixample evening routes feel distinct from Gracia and old-town bar runs.",
    area: "eixample",
    macro: "central-grid",
    tags_intents: ["nightlife", "food_drink", "classic"],
    time_fit: ["evening", "late"],
    route_role: ["bar_anchor", "final"],
    classification: "classic",
    needs_human_verification: false,
  },
  "fabrica-moritz-barcelona": {
    source_url: "https://www.moritz.cat/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "A central beer/food anchor that strengthens Sant Antoni edge routes without making one venue disproportionately important.",
    area: "sant-antoni",
    macro: "central-grid",
    tags_intents: ["food_drink", "nightlife", "classic"],
    time_fit: ["lunch", "evening"],
    route_role: ["food_anchor", "bar_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
  "la-central-mallorca": {
    source_url: "https://lacentral.com/web/librerias/LaCentral/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "An Eixample bookshop anchor that adds culture/shopping density without leaning on museum-only routes.",
    area: "eixample",
    macro: "central-grid",
    tags_intents: ["shopping", "culture", "low_key"],
    time_fit: ["morning", "afternoon"],
    route_role: ["shop_anchor", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "garage-beer-co": {
    source_url: "https://garagebeer.co/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "A beer-led Eixample anchor that helps nightlife routes separate from wine/culture tracks without needing old-town gravity.",
    area: "eixample",
    macro: "central-grid",
    tags_intents: ["food_drink", "nightlife", "low_key"],
    time_fit: ["afternoon", "evening", "late"],
    route_role: ["bar_anchor", "final"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "filmoteca-catalunya": {
    source_url: "https://www.filmoteca.cat/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Selective Raval addition that improves culture depth without adding another generic old-town food stop.",
    area: "raval",
    macro: "old-town",
    tags_intents: ["culture", "low_key", "hidden_gems"],
    time_fit: ["afternoon", "evening"],
    route_role: ["culture_anchor", "middle"],
    classification: "local_anchor",
    needs_human_verification: false,
  },
  "born-museu-historia-barcelona": {
    source_url: "http://elbornculturaimemoria.barcelona.cat",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Selective Born addition that adds a serious culture/history stop without defaulting to a postcard loop.",
    area: "born-sant-pere-santa-caterina",
    macro: "old-town",
    tags_intents: ["culture", "classic", "hidden_gems"],
    time_fit: ["morning", "afternoon"],
    route_role: ["culture_anchor", "middle"],
    classification: "classic",
    needs_human_verification: false,
  },
};

const normalizedItemsByName = new Map();
for (const item of allItems) {
  const aliases = [item.name, ...(item.searchTerms || [])];
  for (const alias of aliases) {
    normalizedItemsByName.set(normalizeLookup(alias), item);
  }
}

function normalizeLookup(value) {
  return String(value || "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
}

function findItemByName(name) {
  return normalizedItemsByName.get(normalizeLookup(name)) || null;
}

module.exports = {
  routeTemplates,
  allItems,
  findItemByName,
  provenanceById,
};
