const LAST_CHECKED = "2026-05-24";

const routeTemplates = [];

const allItems = [
  // --- monastiraki-psyrri (6) ---
  {
    id: "athens-six-dogs",
    name: "Six d.o.g.s",
    kind: "bar",
    lat: 37.977604,
    lng: 23.726746,
    area: "monastiraki-psyrri",
    tags: ["nattliv", "kväll", "musik", "hidden gems", "lokalt"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["six dogs", "six d.o.g.s", "avramiotou", "psyrri bar"],
  },
  {
    id: "athens-varvakeios-central-market",
    name: "Varvakeios Central Market",
    kind: "market",
    lat: 37.980368,
    lng: 23.727242,
    area: "monastiraki-psyrri",
    tags: ["mat", "market", "klassiker", "lokalt"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["varvakeios", "central market", "athinas street", "agora"],
  },
  {
    id: "athens-avissinias-flea-market",
    name: "Avissinias Flea Market",
    kind: "market",
    lat: 37.976421,
    lng: 23.723905,
    area: "monastiraki-psyrri",
    tags: ["shopping", "vintage", "klassiker", "lokalt", "hidden gems"],
    weatherTags: ["sun", "all-weather"],
    searchTerms: ["avissinias", "flea market", "monastiraki flea", "loppis"],
  },
  {
    id: "athens-diporto",
    name: "Diporto",
    kind: "taverna",
    lat: 37.980734,
    lng: 23.725835,
    area: "monastiraki-psyrri",
    tags: ["mat", "lokalt", "klassiker", "hidden gems"],
    weatherTags: ["all-weather"],
    closedWeekdays: [0],
    searchTerms: ["diporto", "sokratous", "theatrou", "central market taverna"],
  },
  {
    id: "athens-klimataria",
    name: "Klimataria",
    kind: "taverna",
    lat: 37.981089,
    lng: 23.724763,
    area: "monastiraki-psyrri",
    tags: ["mat", "musik", "klassiker", "nattliv", "kväll", "lokalt"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["klimataria", "plateia theatrou", "rembetika", "live music taverna"],
  },
  {
    id: "athens-taf-foundation",
    name: "TAF - The Art Foundation",
    kind: "gallery",
    lat: 37.976506,
    lng: 23.724403,
    area: "monastiraki-psyrri",
    tags: ["kultur", "kväll", "hidden gems", "lokalt"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["taf", "the art foundation", "normanou", "monastiraki gallery"],
  },
  {
    id: "athens-couleur-locale",
    name: "Couleur Locale",
    kind: "rooftop-bar",
    lat: 37.976833,
    lng: 23.724203,
    area: "monastiraki-psyrri",
    tags: ["nattliv", "utsikt", "kväll", "cocktail", "hidden gems", "lokalt"],
    weatherTags: ["evening", "golden-hour", "sun"],
    searchTerms: ["couleur locale", "monastiraki rooftop", "normanou rooftop", "rooftop bar"],
  },
  {
    id: "athens-dope-roasting-co",
    name: "Dope Roasting Co.",
    kind: "cafe",
    lat: 37.978903,
    lng: 23.725966,
    area: "monastiraki-psyrri",
    tags: ["mat", "cafe", "coffee", "lokalt", "hidden gems"],
    weatherTags: ["all-weather", "morning"],
    searchTerms: ["dope roasting", "dope coffee", "athinas cafe", "monastiraki cafe"],
  },
  // --- kolonaki-lycabettus (4) ---
  {
    id: "athens-benaki-museum-main",
    name: "Benaki Museum of Greek Culture",
    kind: "museum",
    lat: 37.976031,
    lng: 23.740345,
    area: "kolonaki-lycabettus",
    tags: ["kultur", "museum", "klassiker"],
    weatherTags: ["all-weather", "rainy-day"],
    closedWeekdays: [2],
    searchTerms: ["benaki", "benaki museum", "koumbari", "greek culture museum"],
  },
  {
    id: "athens-museum-of-cycladic-art",
    name: "Museum of Cycladic Art",
    kind: "museum",
    lat: 37.975697,
    lng: 23.742307,
    area: "kolonaki-lycabettus",
    tags: ["kultur", "museum", "klassiker"],
    weatherTags: ["all-weather", "rainy-day"],
    closedWeekdays: [2],
    searchTerms: ["cycladic", "cycladic art", "neophytou douka", "kolonaki museum"],
  },
  {
    id: "athens-lycabettus-hill",
    name: "Lycabettus Hill",
    kind: "viewpoint",
    lat: 37.980316,
    lng: 23.744006,
    area: "kolonaki-lycabettus",
    tags: ["utsikt", "klassiker", "sun", "golden-hour"],
    weatherTags: ["sun", "golden-hour"],
    searchTerms: ["lycabettus", "lykavittos", "funicular", "hill viewpoint"],
  },
  {
    id: "athens-politeia-bookshop",
    name: "Politeia Bookshop",
    kind: "bookshop",
    lat: 37.981881,
    lng: 23.734593,
    area: "kolonaki-lycabettus",
    tags: ["kultur", "shopping", "lokalt"],
    weatherTags: ["all-weather", "rainy-day"],
    closedWeekdays: [0],
    searchTerms: ["politeia", "politeia bookshop", "asklipiou", "bookstore athens"],
  },
  // --- gazi-kerameikos (3) ---
  {
    id: "athens-bios",
    name: "Bios",
    kind: "cultural-venue",
    lat: 37.979835,
    lng: 23.718030,
    area: "gazi-kerameikos",
    tags: ["nattliv", "kultur", "musik", "kväll", "hidden gems"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["bios", "pireos 84", "gazi venue", "rooftop bar"],
  },
  {
    id: "athens-technopolis",
    name: "Technopolis",
    kind: "cultural-venue",
    lat: 37.978565,
    lng: 23.711477,
    area: "gazi-kerameikos",
    tags: ["kultur", "musik", "kväll", "klassiker"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["technopolis", "pireos 100", "gazi", "jazz festival"],
  },
  {
    id: "athens-latraac",
    name: "Latraac",
    kind: "cafe-bar",
    lat: 37.981693,
    lng: 23.713254,
    area: "gazi-kerameikos",
    tags: ["cafe", "nattliv", "kväll", "musik", "lokalt", "hidden gems"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["latraac", "kerameikos skate bowl", "leonidou cafe", "metaxourgeio bar"],
  },
  {
    id: "athens-romantso",
    name: "Romantso",
    kind: "cultural-venue",
    lat: 37.982291,
    lng: 23.725954,
    area: "gazi-kerameikos",
    tags: ["kultur", "kväll", "hidden gems", "lokalt"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["romantso", "anaxagora", "bios romantso", "creative hub"],
  },
  // --- koukaki-makrygianni (2) ---
  {
    id: "athens-acropolis-museum",
    name: "Acropolis Museum",
    kind: "museum",
    lat: 37.968533,
    lng: 23.728471,
    area: "koukaki-makrygianni",
    tags: ["kultur", "museum", "klassiker"],
    weatherTags: ["all-weather", "rainy-day"],
    closedWeekdays: [1],
    searchTerms: ["acropolis museum", "akropolis", "dionysiou areopagitou"],
  },
  {
    id: "athens-little-tree-books-coffee",
    name: "Little Tree Books & Coffee",
    kind: "cafe",
    lat: 37.968190,
    lng: 23.727169,
    area: "koukaki-makrygianni",
    tags: ["kultur", "mat", "lokalt", "hidden gems"],
    weatherTags: ["all-weather", "rainy-day"],
    closedWeekdays: [1],
    searchTerms: ["little tree", "kavalloti", "koukaki cafe", "bookshop cafe"],
  },
  {
    id: "athens-emst",
    name: "EMST - National Museum of Contemporary Art",
    kind: "museum",
    lat: 37.964685,
    lng: 23.728092,
    area: "koukaki-makrygianni",
    tags: ["kultur", "museum", "contemporary", "klassiker", "rainy-day"],
    weatherTags: ["all-weather", "rainy-day"],
    closedWeekdays: [2],
    searchTerms: ["emst", "national museum of contemporary art", "fix museum", "syngrou"],
  },
  // --- exarchia (2) ---
  {
    id: "athens-ama-lachei-stis-nefelis",
    name: "Ama Lachei stis Nefelis",
    kind: "taverna",
    lat: 37.988095,
    lng: 23.736825,
    area: "exarchia",
    tags: ["mat", "lokalt", "kväll", "hidden gems"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["ama lachei", "kallidromiou", "exarchia mezedopoleio", "courtyard"],
  },
  {
    id: "athens-alexandrino",
    name: "Alexandrino",
    kind: "cafe",
    lat: 37.986069,
    lng: 23.735621,
    area: "exarchia",
    tags: ["mat", "kväll", "lokalt", "hidden gems"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["alexandrino", "emmanouil benaki", "exarchia cafe", "bistrot"],
  },
  {
    id: "athens-kallidromiou-market",
    name: "Kallidromiou Farmers' Market",
    kind: "market",
    lat: 37.987861,
    lng: 23.736049,
    area: "exarchia",
    tags: ["market", "mat", "lokalt", "morgon", "hidden gems"],
    weatherTags: ["sun", "morning"],
    closedWeekdays: [0, 1, 2, 3, 4, 5],
    searchTerms: ["kallidromiou market", "laiki agora exarchia", "farmers market", "saturday market"],
  },
  // --- pangrati-mets (2) ---
  {
    id: "athens-national-garden",
    name: "National Garden",
    kind: "park",
    lat: 37.973771,
    lng: 23.737612,
    area: "pangrati-mets",
    tags: ["grönt", "promenad", "utsikt", "klassiker", "lokalt"],
    weatherTags: ["sun", "green-walk"],
    searchTerms: ["national garden", "ethnikos kipos", "zappeion garden", "athens park"],
  },
  {
    id: "athens-karavitis-taverna",
    name: "Karavitis Taverna",
    kind: "taverna",
    lat: 37.971445,
    lng: 23.743573,
    area: "pangrati-mets",
    tags: ["mat", "klassiker", "lokalt", "kväll"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["karavitis", "pafsaniou", "pangrati taverna"],
  },
  {
    id: "athens-mavro-provato",
    name: "Mavro Provato",
    kind: "taverna",
    lat: 37.971489,
    lng: 23.745014,
    area: "pangrati-mets",
    tags: ["mat", "lokalt", "kväll", "hidden gems"],
    weatherTags: ["all-weather", "evening"],
    searchTerms: ["mavro provato", "arrianou", "pangrati mezedopoleio"],
  },
  // --- kypseli (1) ---
  {
    id: "athens-kypseli-municipal-market",
    name: "Kypseli Municipal Market",
    kind: "market",
    lat: 38.000697,
    lng: 23.737837,
    area: "kypseli",
    tags: ["kultur", "market", "lokalt", "hidden gems"],
    weatherTags: ["all-weather"],
    searchTerms: ["kypseli market", "fokionos negri", "dimotiki agora", "municipal market"],
  },
];

const provenanceById = {
  "athens-acropolis-museum": {
    source_url: "https://www.theacropolismuseum.gr/en",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Major museum anchor for Koukaki-Makrygianni routes; verified operator and hours.",
    area: "koukaki-makrygianni",
    macro: "south",
    tags_intents: ["culture", "museum"],
    time_fit: ["morning", "afternoon"],
    route_role: ["main_stop", "neighborhood_anchor"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Dionysiou Areopagitou 15 coordinates. Corroborated: theacropolismuseum.gr + thisisathens.org.",
  },
  "athens-six-dogs": {
    source_url: "https://www.thisisathens.org/nightlife/six-dogs",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Multi-format venue (bar/club/garden/cafe) and future Live source candidate for Monastiraki-Psyrri evening routes.",
    area: "monastiraki-psyrri",
    macro: "central",
    tags_intents: ["nightlife", "live_event"],
    time_fit: ["evening", "night"],
    route_role: ["main_stop", "evening_anchor"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Avramiotou street coordinates. Corroborated: thisisathens.org + ra.co + songkick.",
  },
  "athens-kypseli-municipal-market": {
    source_url: "https://www.thisisathens.org/attractions/kypseli-municipal-market",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Municipal market/culture hub anchoring the Kypseli neighborhood; future event source candidate.",
    area: "kypseli",
    macro: "north",
    tags_intents: ["culture", "market", "local"],
    time_fit: ["morning", "afternoon"],
    route_role: ["main_stop", "neighborhood_anchor"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed 42 Fokionos Negri coordinates. Corroborated: thisisathens.org + cultureisathens.gr + gtp.gr.",
  },
  "athens-varvakeios-central-market": {
    source_url: "https://www.thisisathens.org/shopping/athens-central-food-market",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Historic central food market on Athinas Street; morning route anchor near Monastiraki.",
    area: "monastiraki-psyrri",
    macro: "central",
    tags_intents: ["food", "market"],
    time_fit: ["morning", "afternoon"],
    route_role: ["main_stop", "neighborhood_anchor"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Athinas Street coordinates. Corroborated: thisisathens.org + discovergreece.com.",
  },
  "athens-avissinias-flea-market": {
    source_url: "https://athens-tourist-information.com/shopping/markets/monastiraki-flea-market",
    source_type: "destination_guide",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Sunday flea market anchoring Monastiraki weekend routes; vintage/shopping discovery.",
    area: "monastiraki-psyrri",
    macro: "central",
    tags_intents: ["shopping", "vintage", "market"],
    time_fit: ["morning", "afternoon"],
    route_role: ["main_stop", "weekend_anchor"],
    classification: "classic",
    needs_human_verification: true,
    source_note: "Nominatim confirmed Plateia Avissinias coordinates. Cited sources are destination guides (athens-tourist-information.com, greeka.com) and Tripadvisor — no operator/municipal page surfaced. Human-verify schedule and continuity before any future Live wiring.",
  },
  "athens-bios": {
    source_url: "https://pireos84.bios.gr/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Multi-space cultural venue at Pireos 84; future Live source candidate for Gazi evening routes.",
    area: "gazi-kerameikos",
    macro: "west",
    tags_intents: ["nightlife", "culture", "live_event"],
    time_fit: ["evening", "night"],
    route_role: ["main_stop", "evening_anchor"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Πειραιώς 84 coordinates. Corroborated: pireos84.bios.gr + thisisathens.org + ra.co.",
  },
  "athens-technopolis": {
    source_url: "https://athens-technopolis.gr/index.php/en/component/djevents/events",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Municipal cultural campus at Pireos 100; future Live source candidate with public event feed.",
    area: "gazi-kerameikos",
    macro: "west",
    tags_intents: ["culture", "live_event", "nightlife"],
    time_fit: ["afternoon", "evening"],
    route_role: ["main_stop", "neighborhood_anchor"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Technopolis Gazi coordinates. Corroborated: athens-technopolis.gr + thisisathens.org + athensfilmoffice.com.",
  },
  "athens-karavitis-taverna": {
    source_url: "https://www.thisisathens.org/restaurants/karavitis",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Long-running neighborhood taverna anchoring Pangrati evening routes.",
    area: "pangrati-mets",
    macro: "east",
    tags_intents: ["food", "local"],
    time_fit: ["evening"],
    route_role: ["main_stop", "evening_anchor"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Pafsaniou 4 coordinates. Corroborated: thisisathens.org + xo.gr.",
  },
  "athens-diporto": {
    source_url: "https://www.thisisathens.org/restaurants/diporto",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Hidden basement taverna near Central Market; route discovery moment for food-focused walks.",
    area: "monastiraki-psyrri",
    macro: "central",
    tags_intents: ["food", "local", "hidden_gem"],
    time_fit: ["morning", "afternoon"],
    route_role: ["main_stop", "connector"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Sokratous/Theatrou intersection coordinates. Corroborated: thisisathens.org + atlasobscura + greekgastronomyguide.gr.",
  },
  "athens-benaki-museum-main": {
    source_url: "https://www.benaki.org/index.php?option=com_buildings&view=visiting&Itemid=886&lang=en",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Major museum at Koumbari/Vas. Sofias; Thursday midnight opening adds unique evening option.",
    area: "kolonaki-lycabettus",
    macro: "northeast",
    tags_intents: ["culture", "museum"],
    time_fit: ["morning", "afternoon", "evening"],
    route_role: ["main_stop", "neighborhood_anchor"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Κουμπάρη 1 coordinates. Corroborated: benaki.org + thisisathens.org.",
  },
  "athens-klimataria": {
    source_url: "https://klimataria.gr/en/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Live rembetika taverna at Plateia Theatrou; evening anchor with Tue-Sat music programming.",
    area: "monastiraki-psyrri",
    macro: "central",
    tags_intents: ["food", "nightlife", "live_music"],
    time_fit: ["afternoon", "evening"],
    route_role: ["main_stop", "evening_anchor"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Plateia Theatrou coordinates. Corroborated: klimataria.gr + thisisathens.org + fodors.com.",
  },
  "athens-museum-of-cycladic-art": {
    source_url: "https://cycladic.gr/en/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Kolonaki culture anchor; Thursday late opening (20:00) adds weekday evening option most museums lack.",
    area: "kolonaki-lycabettus",
    macro: "northeast",
    tags_intents: ["culture", "museum"],
    time_fit: ["morning", "afternoon", "evening"],
    route_role: ["main_stop", "rainy_day"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed 4 Neophytou Douka (Kolonaki) coordinates. Corroborated: cycladic.gr + thisisathens.org + discovergreece.com.",
  },
  "athens-taf-foundation": {
    source_url: "https://www.thisisathens.org/arts-entertainment/taf-art-foundation",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Hidden courtyard gallery/bar at Normanou 5; evening culture anchor for Monastiraki routes.",
    area: "monastiraki-psyrri",
    macro: "central",
    tags_intents: ["culture", "nightlife", "hidden_gem"],
    time_fit: ["afternoon", "evening"],
    route_role: ["main_stop", "connector"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Normanou 5 coordinates. Corroborated: thisisathens.org + currentathens.gr + tripadvisor.",
  },
  "athens-couleur-locale": {
    source_url: "https://couleurlocaleathens.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Rooftop bar with direct Acropolis-facing view; strong golden-hour and evening anchor for Monastiraki field tests.",
    area: "monastiraki-psyrri",
    macro: "central",
    tags_intents: ["nightlife", "viewpoint", "golden_hour"],
    time_fit: ["afternoon", "evening", "night"],
    route_role: ["main_stop", "evening_anchor"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Normanou 3 coordinates. Corroborated: couleurlocaleathens.com + thisisathens.org + athens24.com.",
  },
  "athens-dope-roasting-co": {
    source_url: "https://www.thisisathens.org/cafes-bakeries/dope-roasting-co",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Specialty coffee anchor near the market spine; helps morning field tests avoid defaulting to tavernas only.",
    area: "monastiraki-psyrri",
    macro: "central",
    tags_intents: ["coffee", "local", "food"],
    time_fit: ["morning", "afternoon"],
    route_role: ["main_stop", "connector"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Athinas 36 coordinates. Corroborated: thisisathens.org + doperoasting.co + tripadvisor.",
  },
  "athens-little-tree-books-coffee": {
    source_url: "https://www.thisisathens.org/cafes-bakeries/little-tree-books-coffee",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Bookshop-cafe at Kavalloti 2; morning/afternoon anchor for Koukaki routes near Acropolis Museum.",
    area: "koukaki-makrygianni",
    macro: "south",
    tags_intents: ["culture", "food", "local"],
    time_fit: ["morning", "afternoon", "evening"],
    route_role: ["main_stop", "connector"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Tripadvisor confirmed Kavalloti 2 coordinates (37.96819, 23.727169). Corroborated: thisisathens.org + athensexperts.com.",
  },
  "athens-emst": {
    source_url: "https://www.emst.gr/en",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Contemporary museum anchor on Syngrou/Fix; expands Koukaki beyond Acropolis-only culture loops.",
    area: "koukaki-makrygianni",
    macro: "south",
    tags_intents: ["culture", "museum", "contemporary"],
    time_fit: ["morning", "afternoon", "evening"],
    route_role: ["main_stop", "neighborhood_anchor"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Kallirrois Avenue coordinates. Corroborated: emst.gr + thisisathens.org.",
  },
  "athens-ama-lachei-stis-nefelis": {
    source_url: "https://www.thisisathens.org/restaurants/ama-lachei-stis-nefelis",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Courtyard mezedopoleio in a converted school; Exarchia evening food anchor.",
    area: "exarchia",
    macro: "central-north",
    tags_intents: ["food", "local", "evening"],
    time_fit: ["evening"],
    route_role: ["main_stop", "evening_anchor"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed 69 Kallidromiou coordinates. Corroborated: thisisathens.org + culinarybackstreets.com + afar.com.",
  },
  "athens-mavro-provato": {
    source_url: "https://culinarybackstreets.com/cities-category/athens/2014/mavro-provato",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Atmospheric modern-meze taverna at Arrianou 31; evening anchor for Pangrati residential routes.",
    area: "pangrati-mets",
    macro: "east",
    tags_intents: ["food", "local", "evening"],
    time_fit: ["evening"],
    route_role: ["main_stop", "evening_anchor"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed 31 Arrianou coordinates. Corroborated: culinarybackstreets.com + e-restaurants.gr + tripadvisor.",
  },
  "athens-lycabettus-hill": {
    source_url: "https://www.orizonteslycabettus.gr/en/information-en/cable-car-tickets",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Highest central viewpoint with funicular access; golden-hour route anchor for Kolonaki.",
    area: "kolonaki-lycabettus",
    macro: "northeast",
    tags_intents: ["viewpoint", "golden_hour"],
    time_fit: ["afternoon", "evening"],
    route_role: ["main_stop", "neighborhood_anchor"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Lycabettus Hill coordinates. Corroborated: orizonteslycabettus.gr + thisisathens.org.",
  },
  "athens-alexandrino": {
    source_url: "https://www.thisisathens.org/nightlife/alexandrino-cafe-bistrot",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "All-day cafe-bistrot-bar at Emmanouil Benaki 69A; fills the Exarchia cafe-bar anchor gap.",
    area: "exarchia",
    macro: "central-north",
    tags_intents: ["food", "nightlife", "local"],
    time_fit: ["afternoon", "evening"],
    route_role: ["main_stop", "connector"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Emmanouil Benaki 69 coordinates. Corroborated: thisisathens.org + tripadvisor.",
  },
  "athens-kallidromiou-market": {
    source_url: "https://www.thisisathens.org/shopping/laiki-markets",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Saturday farmers' market on Kallidromiou; time-sensitive local market anchor for Exarchia field tests.",
    area: "exarchia",
    macro: "central-north",
    tags_intents: ["market", "food", "local"],
    time_fit: ["morning"],
    route_role: ["main_stop", "market_anchor"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Street-market coordinates centered on Kallidromiou. Corroborated: thisisathens.org laiki-markets guide + local Athens coverage.",
  },
  "athens-latraac": {
    source_url: "https://www.latraac.com/",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Skate-bowl cafe-bar with outdoor linger potential; useful crossover anchor for Gazi/Kerameikos field tests.",
    area: "gazi-kerameikos",
    macro: "west",
    tags_intents: ["coffee", "nightlife", "local"],
    time_fit: ["afternoon", "evening"],
    route_role: ["main_stop", "connector"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Leonidou 63-65 coordinates. Corroborated: latraac.com + thisisathens.org + athensvoice.gr.",
  },
  "athens-national-garden": {
    source_url: "https://www.thisisathens.org/attractions/national-garden",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Walkable green anchor between Syntagma and Pangrati; gives preview users a verified soft scenic loop option.",
    area: "pangrati-mets",
    macro: "east",
    tags_intents: ["green_walk", "scenic", "local"],
    time_fit: ["morning", "afternoon"],
    route_role: ["main_stop", "connector"],
    classification: "classic",
    needs_human_verification: false,
    source_note: "Nominatim confirmed National Garden entrance coordinates. Corroborated: thisisathens.org + visitgreece.gr.",
  },
  "athens-romantso": {
    source_url: "https://www.romantso.gr/?Lang=En",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Creative hub/cultural center at Anaxagora 3-5 (physical address: Metaxourgeio; area-model folded into gazi-kerameikos for v1). Operator is Bios.Romantso.",
    area: "gazi-kerameikos",
    macro: "west",
    tags_intents: ["culture", "nightlife", "local"],
    time_fit: ["afternoon", "evening"],
    route_role: ["main_stop", "connector"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Anaxagora 3 coordinates. Physical address: Metaxourgeio. Folded into gazi-kerameikos per v0.2 area-model decision. Corroborated: romantso.gr + xo.gr + creativehubs.net.",
  },
  "athens-politeia-bookshop": {
    source_url: "https://www.thisisathens.org/shopping/politeia-bookstore",
    source_type: "official_site",
    confidence: "high",
    last_checked: LAST_CHECKED,
    why_included: "Major bookshop at Asklipiou 1-3 near National Library; daytime culture anchor for Kolonaki routes.",
    area: "kolonaki-lycabettus",
    macro: "northeast",
    tags_intents: ["culture", "shopping", "local"],
    time_fit: ["morning", "afternoon"],
    route_role: ["main_stop", "connector"],
    classification: "local_anchor",
    needs_human_verification: false,
    source_note: "Nominatim confirmed Asklipiou 1 coordinates. Corroborated: thisisathens.org + xo.gr + athensisback.gr.",
  },
};

function normalize(value) {
  return String(value || "").trim().toLowerCase();
}

function findItemByName(name) {
  const normalized = normalize(name);
  if (!normalized) return null;
  return (
    allItems.find((item) => normalize(item.name) === normalized) ||
    allItems.find((item) => (item.searchTerms || []).some((term) => normalize(term) === normalized)) ||
    null
  );
}

module.exports = {
  routeTemplates,
  allItems,
  provenanceById,
  findItemByName,
};
